# Generated by Django 5.1 on 2024-08-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_taskstatus_options_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasknote',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
