# Generated by Django 5.1 on 2024-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tasknote_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=1024, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='note',
            field=models.TextField(max_length=1024, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(max_length=128, verbose_name='Статус задачи'),
        ),
    ]
