# Generated by Django 5.1 on 2024-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback_alter_task_task_alter_tasknote_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(max_length=1024, verbose_name='Задача'),
        ),
    ]
