# Generated by Django 5.1 on 2024-09-23 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_task'),
        ('user', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profile_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='profile_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to', to='user.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasknote',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_notes', to='user.profile'),
            preserve_default=False,
        ),
    ]
